builds:
  - binary: tn
    goos:
      - linux
    goarch:
      - amd64
      - 386
archive:
  format: tar.gz
  name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
release:
  github:
    owner: ak1ra24
    name: tinet-go
