name: golangci

on: [push]

jobs:
  build:
    name: all
    runs-on: ubuntu-latest
    strategy:
        matrix:
            go:
            - 1.12.9
    steps:
      - name: checkout
        uses: actions/checkout@v1

      - name: set up Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
        id: go

      - name: cache
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: download modules
        if: steps.cache.outputs.cache-hit != 'true'
        run: go mod download

      - name: Install golangci-lint
        run: |
          curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s v1.17.1
          sudo mv ./bin/golangci-lint $GOPATH/bin/
            
      - name: lint
        run: golangci-lint run

      - name: test
        run: go test ./... -v
